import "./globals.css"
import Navbar from "./components/Navbar";
import { Poppins } from "next/font/google"
import Footer from "./components/Footer";
import { ToastContainer, Slide } from "react-toastify"
import "react-toastify/dist/ReactToastify.css"

const poppins = Poppins({
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
	subsets: ["latin"],
	display: "swap",
	variable: "--font-poppins",
})

export const metadata = {
  title: "Nas Tech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en' suppressHydrationWarning>
			
			<body className={`${poppins.className} antialiased`}>
			<ToastContainer
					className={"w-[400px] text-center font-semibold text-[16px] duration-700"}
					position='top-center'
					autoClose={3000}
					hideProgressBar={false}
					newestOnTop={false}
					closeOnClick
					rtl={false}
					pauseOnFocusLoss={false}
					draggable={false}
					pauseOnHover={false}
					theme='light'
					transition={Slide}
					
				/>
				<Navbar />
				
				<main>{children}</main>

				<Footer />

			</body>
		</html>
	)
}
